---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sourcebot.fullname" $ }}
  labels:
    {{- include "sourcebot.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.sourcebot.replicaCount }}
  selector:
    matchLabels:
      {{- include "sourcebot.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- with $.Values.sourcebot.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sourcebot.labels" $ | nindent 8 }}
    spec:
      {{- with $.Values.sourcebot.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sourcebot.serviceAccountName" $ }}
      {{- if $.Values.sourcebot.podSecurityContext }}
      securityContext:
        {{- toYaml $.Values.sourcebot.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- with $.Values.sourcebot.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with $.Values.sourcebot.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "sourcebot.image" $ }}
          imagePullPolicy: {{ $.Values.sourcebot.image.pullPolicy }}
          {{- with $.Values.sourcebot.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.sourcebot.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.sourcebot.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- if and $.Values.sourcebot.ingress.enabled (gt (len $.Values.sourcebot.ingress.hosts) 0) }}
            - name: AUTH_URL
              value: {{ (index $.Values.sourcebot.ingress.hosts 0).host | printf "https://%s" }}
            {{- end }}
            - name: CONFIG_PATH
              value: /etc/sourcebot/config.json
            {{- if or $.Values.sourcebot.license.value $.Values.sourcebot.license.existingSecret }}
            - name: SOURCEBOT_EE_LICENSE_KEY
              {{- with (include "sourcebot.getValueOrSecret" (dict "value" $.Values.sourcebot.license)) }}
              {{- . | nindent 14 }}
              {{- end }}
            {{- end }}
            {{- include "sourcebot.databaseEnv" . | nindent 12 }}
            {{- include "sourcebot.redisEnv" . | nindent 12 }}
            {{- range $.Values.sourcebot.additionalEnvSecrets }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
            {{- with $.Values.sourcebot.additionalEnv }}
            {{- toYaml . | nindent  12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $.Values.sourcebot.service.containerPort }}
              protocol: TCP
            {{- range $.Values.sourcebot.additionalPorts }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- with $.Values.sourcebot.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.sourcebot.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.sourcebot.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.sourcebot.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: sourcebot-config
              mountPath: /etc/sourcebot/config.json
              subPath: config.json
              readOnly: true
            {{- if .Values.sourcebot.persistence.enabled }}
            - name: sourcebot-data
              mountPath: /data
            {{- end }}
          {{- with $.Values.sourcebot.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $.Values.sourcebot.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      volumes:
        - name: sourcebot-config
          configMap:
            name: {{ include "sourcebot.fullname" $ }}
            items:
              - key: config.json
                path: config.json
        {{- if .Values.sourcebot.persistence.enabled }}
        - name: sourcebot-data
          persistentVolumeClaim:
            claimName: {{ .Values.sourcebot.persistence.existingClaim | default (printf "%s-data" (include "sourcebot.fullname" .)) }}
        {{- end }}
      {{- with $.Values.sourcebot.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.sourcebot.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.sourcebot.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.sourcebot.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
