{{- if $.Values.sourcebot.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sourcebot.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "sourcebot.labels" . | nindent 4 }}
  {{- with $.Values.sourcebot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.sourcebot.serviceAccount.automount }}
{{- end }}
